[theme]
base = "dark"
primaryColor = "#4fb9c4"
backgroundColor = "#141414"
secondaryBackgroundColor = "#222222"
textColor = "#e8e8e8"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
